sudo: false
dist: trusty
language: node_js
cache: npm
node_js:
  - "8"
script:
  - "npm install vuepress"
  - "npm run docs:build"
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: .vuepress/dist
  keep-history: true
  on:
    repo: andrecedik/shipcloud-docs-vuepress
    branch: master
  skip_cleanup: true
